import { NextResponse } from "next/server";
import { syncGoogleSheet } from "@/lib/google-sheets";
import { sendTelegram } from "@/lib/telegram";
const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
export async function POST(request: Request) {
  if (!url || !serviceKey) return NextResponse.json({ error: "Server connection is not configured." }, { status: 503 });
  const body = await request.json() as Record<string, unknown>;
  const headers = { apikey: serviceKey, Authorization: `Bearer ${serviceKey}`, "Content-Type": "application/json" };
  const manager = await (await fetch(`${url}/rest/v1/employees?id=eq.${body.managerId}&select=role`, { headers })).json() as Array<{ role: string }>;
  if (manager[0]?.role !== "manager") return NextResponse.json({ error: "Only Svetlana can make decisions." }, { status: 403 });
  const reference = String(body.reference ?? "").trim().toUpperCase();
  const markDelivery = (table: "sales" | "expenses", id: unknown, sent: boolean) => fetch(`${url}/rest/v1/${table}?id=eq.${id}`, { method: "PATCH", headers, body: JSON.stringify({ notification_status: sent ? "sent" : "failed" }) });
  if (body.type === "sale") { const shares = [Number(body.richard), Number(body.anastasia), Number(body.jeanClaude)]; if (!reference || shares.some((share) => share < 0 || share > 100) || shares.reduce((sum, share) => sum + share, 0) !== 100) return NextResponse.json({ error: "Use a reference and commission shares totalling 100%." }, { status: 400 }); const response = await fetch(`${url}/rest/v1/sales?reference=eq.${reference}&status=eq.pending_approval`, { method: "PATCH", headers: { ...headers, Prefer: "return=representation" }, body: JSON.stringify({ status: "approved", approved_richard_percent: shares[0], approved_anastasia_percent: shares[1], approved_jean_claude_percent: shares[2], approved_at: new Date().toISOString() }) }); const updated = await response.json() as Record<string, unknown>[]; if (response.ok && updated.length) { const sale=updated[0]; let synced=true; try { synced=await syncGoogleSheet("Sales", sale); } catch { synced=false; } const staff=await (await fetch(`${url}/rest/v1/employees?id=eq.${sale.salesperson_id}&select=telegram_chat_id`,{headers})).json() as Array<{telegram_chat_id:number|null}>; const pool=Number(sale.amount)*.1; const changed=shares.some((share,index)=>share!==Number([sale.proposed_richard_percent,sale.proposed_anastasia_percent,sale.proposed_jean_claude_percent][index])); const note=await sendTelegram(Number(sale.telegram_chat_id) || staff[0]?.telegram_chat_id,`${reference} approved${changed ? " — commission split changed" : ""}. Sale €${Number(sale.amount).toFixed(2)}; total commission €${pool.toFixed(2)}. Richard ${shares[0]}% (€${(pool*shares[0]/100).toFixed(2)}), Anastasia ${shares[1]}% (€${(pool*shares[1]/100).toFixed(2)}), Jean-Claude ${shares[2]}% (€${(pool*shares[2]/100).toFixed(2)}).`); await markDelivery("sales",sale.id,note.sent); await fetch(`${url}/rest/v1/sales?id=eq.${sale.id}`,{method:"PATCH",headers,body:JSON.stringify({sync_status:synced?"synced":"failed"})}); return NextResponse.json({ message: `${reference} approved.${synced ? "" : " Google Sheets sync failed — retry it."} ${note.sent ? "Telegram notification sent." : note.reason}` }); } return NextResponse.json({ error: "Sale was not found or is already approved." }, { status: 400 }); }
  if (body.type === "expense") { const allocation = String(body.allocation ?? ""); if (!reference || !["A", "B", "Company overhead"].includes(allocation)) return NextResponse.json({ error: "Use a reference and a valid allocation." }, { status: 400 }); const response = await fetch(`${url}/rest/v1/expenses?reference=eq.${reference}&status=eq.awaiting_allocation`, { method: "PATCH", headers: { ...headers, Prefer: "return=representation" }, body: JSON.stringify({ status: "allocated", final_allocation: allocation, allocated_at: new Date().toISOString() }) }); const updated = await response.json() as Record<string, unknown>[]; if (response.ok && updated.length) { const expense=updated[0]; let synced=true; try { synced=await syncGoogleSheet("Expenses",expense); } catch { synced=false; } const staff=await (await fetch(`${url}/rest/v1/employees?id=eq.${expense.reporter_id}&select=telegram_chat_id`,{headers})).json() as Array<{telegram_chat_id:number|null}>; const changed=allocation!==String(expense.proposed_allocation); const note=await sendTelegram(Number(expense.telegram_chat_id) || staff[0]?.telegram_chat_id,`${reference} allocated${changed ? " — allocation changed" : ""}. €${Number(expense.amount).toFixed(2)}: ${String(expense.description)}. Final allocation: ${allocation}.`); await markDelivery("expenses",expense.id,note.sent); await fetch(`${url}/rest/v1/expenses?id=eq.${expense.id}`,{method:"PATCH",headers,body:JSON.stringify({sync_status:synced?"synced":"failed"})}); return NextResponse.json({ message: `${reference} allocated to ${allocation}.${synced ? "" : " Google Sheets sync failed — retry it."} ${note.sent ? "Telegram notification sent." : note.reason}` }); } return NextResponse.json({ error: "Expense was not found or is already allocated." }, { status: 400 }); }
  return NextResponse.json({ error: "Choose a decision type." }, { status: 400 });
}
