"use client";

import { useState } from "react";
import type { Employee } from "@/app/page";

const roleLabel = { manager: "Manager", salesperson: "Salesperson", expense_reporter: "Expense reporter" };

export function DemoDashboard({ staff, stats, details, pending }: { staff: Employee[]; stats: { projectA: number; projectB: number; company: number }; details: { pendingSales: number; awaitingExpenses: number; overhead: number; richard: number; anastasia: number; jeanClaude: number }; pending: { sales: string[]; expenses: string[] } }) {
  const [selectedId, setSelectedId] = useState(staff[0]?.id ?? "");
  const selected = staff.find((employee) => employee.id === selectedId);
  const isManager = selected?.role === "manager";
  const canSubmitSale = selected?.role === "salesperson";
  const canSubmitExpense = selected?.role === "expense_reporter";
  return <main className="shell">
    <header className="topbar"><div><p className="eyebrow">Friends Included Ltd · Katrina Nemirovska</p><h1>Finance system</h1></div><div className="connection"><span className="status-dot" /> Supabase connected</div></header>
    <section className="role-panel"><div><p className="section-label">Demonstration access</p><h2>Who are you today?</h2><p>Choose a fictional employee to test what they can see and do.</p></div><label className="role-select"><span>Demonstration role</span><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{staff.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} — {roleLabel[employee.role]}</option>)}</select></label></section>
    {selected ? <section className="welcome"><div><p className="section-label">Signed in for demonstration</p><h2>{selected.name}</h2><p>{roleLabel[selected.role]}</p></div><div className="permission-summary">{isManager && "You can review and approve records."}{canSubmitSale && "You can report sales and proposed commission splits."}{canSubmitExpense && "You can report expenses and proposed allocations."}</div></section> : <p className="empty-state">Employee data is loading. Refresh the page if it does not appear.</p>}
    <section className="metrics"><Metric label="Project A result" value={formatMoney(stats.projectA)} detail="Approved sales, commissions and expenses" /><Metric label="Project B result" value={formatMoney(stats.projectB)} detail="Approved sales, commissions and expenses" /><Metric label="Company result" value={formatMoney(stats.company)} detail="All recorded expenses included" featured /></section>
    <section className="workspace-card"><p className="section-label">Financial detail</p><h2>Live finance summary</h2><p>Pending sales: {details.pendingSales}. Expenses awaiting allocation: {details.awaitingExpenses}. Company overhead: {formatMoney(details.overhead)}.</p><p>Commission earned — Richard: {formatMoney(details.richard)}; Anastasia: {formatMoney(details.anastasia)}; Jean-Claude: {formatMoney(details.jeanClaude)}.</p></section>
    <section className="workspace-card sale-form"><p className="section-label">How to use</p><h2>Demonstration instructions</h2><p>Choose a salesperson to submit a sale, Kevin to report an expense, or Svetlana to link Telegram users, approve sales and allocate expenses. Pending records do not affect project income until Svetlana makes a decision.</p></section>
    {canSubmitSale && selected ? <SaleForm employeeId={selected.id} /> : canSubmitExpense && selected ? <ExpenseForm employeeId={selected.id} /> : isManager && selected ? <ManagerSetup managerId={selected.id} staff={staff} pending={pending} /> : <section className="workspace"><div className="workspace-card"><p className="section-label">Next action</p><h2>Choose a role</h2></div></section>}
    <footer className="project-links"><p className="section-label">Project links</p><div><a href="https://t.me/FIF_KN_bot" target="_blank" rel="noreferrer">Telegram bot</a><a href="https://docs.google.com/spreadsheets/d/1NzIgULfKfVuHIYNWbxawqqCOQZa2KKJowVy5JQA7kwk/edit?usp=sharing" target="_blank" rel="noreferrer">Google Sheets ledger</a><a href="https://github.com/katrinanemirovska-hub/friends-included-finance" target="_blank" rel="noreferrer">GitHub repository</a></div></footer>
  </main>;
}

function Metric({ label, value, detail, featured = false }: { label: string; value: string; detail: string; featured?: boolean }) { return <article className={`metric ${featured ? "metric-featured" : ""}`}><p>{label}</p><strong>{value}</strong><span>{detail}</span></article>; }
function formatMoney(value: number) { return new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR" }).format(value); }

function SaleForm({ employeeId }: { employeeId: string }) {
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const values = new FormData(event.currentTarget); const response = await fetch("/api/sales", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId, reference: values.get("reference"), customer: values.get("customer"), project: values.get("project"), description: values.get("description"), amount: Number(values.get("amount")), richardPercent: Number(values.get("richardPercent")), anastasiaPercent: Number(values.get("anastasiaPercent")), jeanClaudePercent: Number(values.get("jeanClaudePercent")) }) }); const result = await response.json() as { message?: string; error?: string }; setMessage(result.message ?? result.error ?? "Could not save the sale."); setSaving(false); if (response.ok) event.currentTarget.reset(); }
  return <form className="workspace-card sale-form" onSubmit={submit}><p className="section-label">New sale</p><h2>Report a sale</h2><p>Every sale is saved as Pending approval. Commission shares must total 100%.</p><div className="form-grid"><label>Reference<input name="reference" placeholder="S01" required /></label><label>Customer<input name="customer" placeholder="Olivia Rose" required /></label><label>Project<select name="project" defaultValue="A"><option value="A">Project A</option><option value="B">Project B</option></select></label><label>Amount (€)<input name="amount" type="number" min="0.01" step="0.01" required /></label><label className="wide-field">Description<textarea name="description" required /></label><label>Richard %<input name="richardPercent" type="number" min="0" max="100" required /></label><label>Anastasia %<input name="anastasiaPercent" type="number" min="0" max="100" required /></label><label>Jean-Claude %<input name="jeanClaudePercent" type="number" min="0" max="100" required /></label></div><div className="form-footer"><button type="submit" disabled={saving}>{saving ? "Saving…" : "Submit sale"}</button>{message && <span>{message}</span>}</div></form>;
}

function ExpenseForm({ employeeId }: { employeeId: string }) {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/expenses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId, reference: values.get("reference"), description: values.get("description"), category: values.get("category"), amount: Number(values.get("amount")), allocation: values.get("allocation") }) }); const result = await response.json() as { message?: string; error?: string }; setMessage(result.message ?? result.error ?? "Could not save the expense."); if (response.ok) event.currentTarget.reset(); }
  return <form className="workspace-card sale-form" onSubmit={submit}><p className="section-label">New expense</p><h2>Report an expense</h2><p>Project expenses wait for Svetlana&apos;s allocation decision. Company overhead is allocated immediately.</p><div className="form-grid"><label>Reference<input name="reference" placeholder="E02" required /></label><label>Amount (€)<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Category<select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><label>Proposed allocation<select name="allocation"><option value="A">Project A</option><option value="B">Project B</option><option value="Company overhead">Company overhead</option></select></label><label className="wide-field">Description<textarea name="description" required /></label></div><div className="form-footer"><button type="submit">Submit expense</button>{message && <span>{message}</span>}</div></form>;
}

function ManagerSetup({ managerId, staff, pending }: { managerId: string; staff: Employee[]; pending: { sales: string[]; expenses: string[] } }) {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/manager/link-telegram", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ managerId, employeeId: values.get("employeeId"), telegramUserId: values.get("telegramUserId") }) }); const result = await response.json() as { message?: string; error?: string }; setMessage(result.message ?? result.error ?? "Could not save the link."); }
  return <><section className="workspace-card sale-form"><p className="section-label">Pending work</p><h2>Records awaiting your decision</h2><p>Sales: {pending.sales.join(" · ") || "None"}</p><p>Expenses: {pending.expenses.join(" · ") || "None"}</p></section><form className="workspace-card sale-form" onSubmit={submit}><p className="section-label">Manager setup</p><h2>Link a Telegram user ID</h2><p>Only Svetlana can link a real Telegram sender to a fictional employee. The bot will then accept that employee&apos;s transactions.</p><div className="form-grid"><label>Employee<select name="employeeId" defaultValue=""> <option value="" disabled>Choose an employee</option>{staff.filter((employee) => employee.role !== "manager").map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label><label>Telegram user ID<input name="telegramUserId" inputMode="numeric" placeholder="1842987870" required /></label></div><div className="form-footer"><button type="submit">Link Telegram account</button>{message && <span>{message}</span>}</div></form><DecisionForm managerId={managerId} /><SheetRetry /></>;
}

function SheetRetry() {
  const [message, setMessage] = useState("");
  async function retry() { setMessage("Synchronising…"); const response = await fetch("/api/sheets/sync", { method: "POST" }); const result = await response.json() as { message?: string; error?: string }; setMessage(result.message ?? result.error ?? "Sync failed. Try again."); }
  return <section className="workspace-card sale-form"><p className="section-label">Google Sheets</p><h2>Retry synchronisation</h2><p>If Sheets is temporarily unavailable, retrying updates existing rows by reference and does not create duplicates.</p><div className="form-footer"><button type="button" onClick={retry}>Retry Google Sheets sync</button>{message && <span>{message}</span>}</div></section>;
}

function DecisionForm({ managerId }: { managerId: string }) {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/manager/decision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ managerId, type: values.get("type"), reference: values.get("reference"), richard: Number(values.get("richard")), anastasia: Number(values.get("anastasia")), jeanClaude: Number(values.get("jeanClaude")), allocation: values.get("allocation") }) }); const result = await response.json() as { message?: string; error?: string }; setMessage(result.message ?? result.error ?? "Could not save the decision."); }
  return <form className="workspace-card sale-form" onSubmit={submit}><p className="section-label">Manager decision</p><h2>Approve a sale or allocate an expense</h2><div className="form-grid"><label>Type<select name="type"><option value="sale">Sale</option><option value="expense">Expense</option></select></label><label>Reference<input name="reference" placeholder="S01 or E01" required /></label><label>Richard %<input name="richard" type="number" defaultValue="0" /></label><label>Anastasia %<input name="anastasia" type="number" defaultValue="0" /></label><label>Jean-Claude %<input name="jeanClaude" type="number" defaultValue="0" /></label><label>Expense allocation<select name="allocation"><option value="A">Project A</option><option value="B">Project B</option><option value="Company overhead">Company overhead</option></select></label></div><div className="form-footer"><button type="submit">Save decision</button>{message && <span>{message}</span>}</div></form>;
}
